### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by Sandile-Dev01** [ahanafasir/omnifood#1]
This project is clean, the user interface, the animations, and the details are pixel perfected.

- I feel like the `border` is a little bit big though when I click on the nav and doesn't provide enough room for the link texts to breathe.

Overall the project is looking good nice work you did there!

**Comment by ahanafasir** [comment]
Hi Sandile,
Thank you for taking the time to review my project and suggesting solutions for the irregularities. I have checked your recommended solutions and found that while the **nav**  links were getting the breathing room through padding, the logos were not and that made it seem a little odd. However, I have added the adjustments to the relevant classes and updated the repo. 

Thanks again! Have a great day!
